"""Hello there! My name is Sam and this is hard

Revision ID: 171adc4758e3
Revises: 932f35dcab3a
Create Date: 2024-07-20 13:10:02.675351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '171adc4758e3'
down_revision = '932f35dcab3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
