"""Hello there! What are you up to?

Revision ID: 807091391c16
Revises: 171adc4758e3
Create Date: 2024-07-20 13:19:57.706729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '807091391c16'
down_revision = '171adc4758e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
